//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIO.Api.SAPTSO.ServiceCustomer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCustomer.IServiceSapTso")]
    public interface IServiceSapTso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSapTso/SetCliente", ReplyAction="http://tempuri.org/IServiceSapTso/SetClienteResponse")]
        string SetCliente(string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSapTso/SetCliente", ReplyAction="http://tempuri.org/IServiceSapTso/SetClienteResponse")]
        System.Threading.Tasks.Task<string> SetClienteAsync(string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSapTso/Test", ReplyAction="http://tempuri.org/IServiceSapTso/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSapTso/Test", ReplyAction="http://tempuri.org/IServiceSapTso/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSapTsoChannel : AIO.Api.SAPTSO.ServiceCustomer.IServiceSapTso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSapTsoClient : System.ServiceModel.ClientBase<AIO.Api.SAPTSO.ServiceCustomer.IServiceSapTso>, AIO.Api.SAPTSO.ServiceCustomer.IServiceSapTso {
        
        public ServiceSapTsoClient() {
        }
        
        public ServiceSapTsoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSapTsoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSapTsoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSapTsoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SetCliente(string cliente) {
            return base.Channel.SetCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<string> SetClienteAsync(string cliente) {
            return base.Channel.SetClienteAsync(cliente);
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
    }
}
